### PR TITLE
Feature/S3C-3567-Create-Account-1

### PR DESCRIPTION
**Pull request by saitharunthodupunuru**
Closed [old PR](https://github.com/scality/vaultclient-java/pull/5) as it is little confusing with big commits.

Created this micro PR#1

**Description:**
Publishing the jar artifact after successful build to OSS Sonatype Nexus Maven repository. As Apache Maven central repository only accepts release artifacts and the only way to publish an artifact to maven central is using open source OSS Nexus repository. We created account at https://oss.sonatype.org/#view-repositories and uploading gpg signed snapshot artifact before release.

References:

https://maven.apache.org/repository/guide-central-repository-upload.html
https://www.albertgao.xyz/2018/01/18/how-to-publish-artifact-to-maven-central-via-gradle/
https://central.sonatype.org/pages/ossrh-guide.html

### CODE REVIEW

**Review by RachedBenMustapha — APPROVED** [review]
Looks good overall. There are some files with extra comments, missing EOL at end of files, and extra blank lines that could introduce spurious diffs in the future. Now might be a good time to clean them up.

**Comment by saitharunthodupunuru** [comment]
> Looks good overall. There are some files with extra comments, missing EOL at end of files, and extra blank lines that could introduce spurious diffs in the future. Now might be a good time to clean them up.

Updated EOLs and removed unwanted spaces, empty lines and comments. Thanks

**Review by anurag4DSB — APPROVED** [review]

**Pull request merged**
