### PR TITLE
Feature/S3C-3567-Create-Account-2

### PR DESCRIPTION
**Pull request by saitharunthodupunuru**
Created this micro PR#2

Description:
* This PR has DTO/POJOs for Create Account API
* Excluded these DTO classes from code coverage

### CODE REVIEW

**Review by ilkescality — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]
LGTM.


Just an idea. If you need to set the tenant ID from the vCloudDirector, if its a 12 digit ID, you can set it too while creating an account with.
https://github.com/scality/vaultclient/blob/development/8.2/lib/IAMClient.js#L137

If it is not required, then we don't need to worry about it now.

**Comment by saitharunthodupunuru** [comment]
> LGTM.
> 
> Just an idea. If you need to set the tenant ID from the vCloudDirector, if its a 12 digit ID, you can set it too while creating an account with.
> https://github.com/scality/vaultclient/blob/development/8.2/lib/IAMClient.js#L137
> 
> If it is not required, then we don't need to worry about it now.

vCloudDirector OSE creates tenants with UUIDs and currently Get Account works only with Name and email address.
So I am storing tenantID in account "name" field. More information on this implementation will be shown in the next PR

**Comment by anurag4DSB** [comment]
> urrently Get Account works only with Name and ema

I disagree with that methodology. We should extend the Vault call. Approving this for now. We need a design doc PR, which will document all these design details and move them from google doc to github. These changes design changes by me on the design doc PR :)

**Pull request merged**
