### PR TITLE
S3C-3736 Printing/Uploading coverage & lint analysis reports

### PR DESCRIPTION
**Pull request by saitharunthodupunuru**
Added code
 
**To Print** 
 - code coverage

**To Upload**
 - code-coverage reports
 - Lint analysis reports by PMD
 - Spotbugs reports
 
Screen Shot 2021-01-07 at 1 49 35 AM

Also added mandatory coverage percentage to **80%**

### CODE REVIEW

**Comment by saitharunthodupunuru** [comment]
Also added mandatory coverage percentage to **80%**

**Comment by miniscruff** [comment]
> Also added mandatory coverage percentage to **80%**

At the moment we do not really have any sort of minimum for coverage, I agree 80% is an ok minimum but choosing it in one project without any sort of discussion might cause an issue.

Also uploading coverage and test artifacts to eve doesn't do a whole lot. I would follow this PR https://github.com/scality/zenko-ui/pull/74 and use codecov ( or do nothing and we can get to it later on )

**Review by jonathan-gramain — APPROVED** [review]
I'm not a fan of enforcing a hard limit as a specific percentage of coverage in general, I fear this has the potential to cause more trouble than benefits, we may end up spending time adding tests here and there where it is not justified to satisfy the rule (similar to how some linter rule abuse exists too). This is just my personal view, for the PR itself it looks good to me so approving.

**Review by tmacro — APPROVED** [review]

**Comment by saitharunthodupunuru** [comment]
> > Also added mandatory coverage percentage to **80%**
> 
> At the moment we do not really have any sort of minimum for coverage, I agree 80% is an ok minimum but choosing it in one project without any sort of discussion might cause an issue.
> 
> Also uploading coverage and test artifacts to eve doesn't do a whole lot. I would follow this PR [scality/zenko-ui#74](https://github.com/scality/zenko-ui/pull/74) and use codecov ( or do nothing and we can get to it later on )
> 
> Edit: The build should fail if any static analysis fails like linting in addition to failing tests.

**Regarding coverage reports:**
Made the changes to include codecov as coverage reporting. I am still keeping the uploading reports part as may be extra information.

**Regarding the lint:**
Yes Gradle builds will fail if static code analysis fails. PMD and Spotbugs are for static code analysis here and these reports are also uploaded in the end. 

**Regarding code coverage 80% limit:**
We decided that 80% is a good number to start with. We can reduce this later if it becomes difficult to maintain and time consuming.

**Pull request merged**
